import "./globals.css";
import Header from "@/components/header/component";
import ContextProvider from "@/components/context-provider/component";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <Header/>
          <main>
            {children}

          </main>
        </ContextProvider>
      </body>
    </html>
  );
}
