import "./globals.css";
import Header from "@/components/header/component";
import ContextProvider from "@/components/context-provider/component";
import DarkOverlay from "@/components/dark-overlay/component";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <Header/>

          <DarkOverlay/>

          <main>
            {children}
          </main>
        </ContextProvider>
      </body>
    </html>
  );
}
