import "./globals.css";
import Header from "@/components/header/component";
import ContextProvider from "@/components/context-provider/component";
import DarkOverlay from "@/components/dark-overlay/component";
import Header2 from "@/components/header2/component";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <Header/>
          <Header2/>

          <main>
            {children}
          </main>

          <DarkOverlay/>
            
        </ContextProvider>
      </body>
    </html>
  );
}
